version: '3.7'
services:
  # postgres://admin:admin@postgres:5432
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: admin
    networks:
      - nestjs

networks:
  nestjs:
